---
  - name: Create DB
    mysql_db: name={{ wp_mysql_db }} state=present
     

  - name: Create User
    mysql_user:
      name: '{{ wp_mysql_user }}' 
      password: '{{ wp_mysql_password }}' 
      priv: '*.*:ALL'
      state: present
